
  CREATE TABLE "RS2"."EMPLOYEE" 
   (	"NAME" VARCHAR2(32), 
	"SALARY" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"